-- Copied from .build_cache/schema.sql for Docker build context
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS USER_DEPT (
    EMP_ID      TEXT        NOT NULL,
    EMP_NAME    TEXT        NOT NULL,
    DEPT_CD     TEXT,
    DEPT_NAME   TEXT        NOT NULL,
    CREATED_AT  TEXT,
    CREATED_TM  TEXT        DEFAULT (datetime('now', 'localtime')),
    UPDATED_AT  TEXT,
    UPDATED_TM  TEXT        DEFAULT (datetime('now', 'localtime')),
    PRIMARY KEY (EMP_ID)
);

CREATE INDEX IF NOT EXISTS idx_user_dept_dept_cd ON USER_DEPT (DEPT_CD);

CREATE TABLE IF NOT EXISTS CHAT_ROOM (
    ROOM_ID     TEXT        NOT NULL,
    ROOM_NAME   TEXT        NOT NULL,
    ROOM_TYPE   TEXT        DEFAULT 'PERSONAL'
                            CHECK (ROOM_TYPE IN ('PERSONAL', 'DEPARTMENT')),
    CREATED_AT  TEXT,
    CREATED_TM  TEXT        DEFAULT (datetime('now', 'localtime')),
    UPDATED_AT  TEXT,
    UPDATED_TM  TEXT        DEFAULT (datetime('now', 'localtime')),
    PRIMARY KEY (ROOM_ID)
);

CREATE INDEX IF NOT EXISTS idx_chat_room_type ON CHAT_ROOM (ROOM_TYPE);

CREATE TABLE IF NOT EXISTS CHAT_ROOM_MEMBER (
    ROOM_ID     TEXT        NOT NULL,
    EMP_ID      TEXT        NOT NULL,
    JOINED_AT   TEXT        DEFAULT (datetime('now', 'localtime')),
    PRIMARY KEY (ROOM_ID, EMP_ID),
    FOREIGN KEY (ROOM_ID) REFERENCES CHAT_ROOM (ROOM_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (EMP_ID)  REFERENCES USER_DEPT (EMP_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_chat_room_member_emp ON CHAT_ROOM_MEMBER (EMP_ID);

CREATE TABLE IF NOT EXISTS CHAT_HISTORY (
    CHAT_ID         TEXT    NOT NULL,
    ROOM_ID         TEXT    NOT NULL,
    EMP_ID          TEXT    NOT NULL,
    MESSAGE         TEXT    NOT NULL,
    USED_YN         INTEGER DEFAULT 1 CHECK (USED_YN IN (0, 1)),
    COMPLIANCE_YN   INTEGER DEFAULT 0 CHECK (COMPLIANCE_YN IN (0, 1)),
    CREATED_AT      TEXT,
    CREATED_TM      TEXT    DEFAULT (datetime('now', 'localtime')),
    UPDATED_AT      TEXT,
    UPDATED_TM      TEXT    DEFAULT (datetime('now', 'localtime')),
    PRIMARY KEY (CHAT_ID),
    FOREIGN KEY (ROOM_ID) REFERENCES CHAT_ROOM (ROOM_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (EMP_ID)  REFERENCES USER_DEPT (EMP_ID)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_chat_history_room_active
    ON CHAT_HISTORY (ROOM_ID, USED_YN, CREATED_TM ASC);
CREATE INDEX IF NOT EXISTS idx_chat_history_emp ON CHAT_HISTORY (EMP_ID);
CREATE INDEX IF NOT EXISTS idx_chat_history_compliance
    ON CHAT_HISTORY (ROOM_ID, COMPLIANCE_YN) WHERE USED_YN = 1;
